---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-secret-creator
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-secret-creator
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-secret-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-secret-creator
subjects:
  - kind: ServiceAccount
    name: cert-secret-creator
    namespace: istio-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-secret-creator
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-secret-creator
  template:
    metadata:
      labels:
        app: cert-secret-creator
    spec:
      containers:
        - image: boeboe/istio-cert-secret-creator:0.1.0
          imagePullPolicy: Always
          name: cert-secret-creator
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
      serviceAccountName: cert-secret-creator